controller_manager:
  ros__parameters:
    update_rate: 100
    
    flipper_controller:
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      publish_rate: 50



flipper_controller:
  ros__parameters:
    joints:
      - front_left_flipper_joint
